http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth:
    host: localhost
    paths: ['/auth/*']
  providers:
    host: localhost
    paths: ['/providers', '/providers/*', 'images-providers/*']
  events:
    host: localhost
    paths: ['/events', '/events/*', 'images-events/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authServices:
    url: 'http://52.71.68.46'
  providersServices:
    url: 'http://54.160.85.181'
  eventsServices:
    url: 'http://54.157.159.108'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  authPipeline:
    apiEndpoints:
      - auth
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authServices 
              changeOrigin: true
  providersPipeline:
    apiEndpoints:
      - providers
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: providersServices 
              changeOrigin: true
  eventsPipeline:
    apiEndpoints:
      - events
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: eventsServices 
  
